language: python
python:
- '2.7'
- '3.5'
env:
- FILENAME=README.md
- FILENAME=PITCHME.md
matrix:
  allow_failures:
    - python: '3.5'
script:
- python -m doctest ${FILENAME}
notifications:
  email: false
